---
- name: Playbook for managing the updates in RPi
  hosts: raspberry_pi
  user: pi
  gather_facts: no
  tasks:
    - name: Update apt package cache
      become: true
      apt:
        update_cache: yes
        upgrade: full